# Page settings

baseURL = "https://ohmykevin.github.io/resume/"
languageCode = "en"
title = ""
theme = "devresume"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Kevin"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Kevin   "
        tagline = "中级运维工程师"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "南京"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "173xxxxxxxx" 
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "941104c@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "dogwin.top"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "技术栈"
        [[params.skills.list.items]]
        details = "Linux 常用命令"
        [[params.skills.list.items]]
        details = "数据库高可用"
        [[params.skills.list.items]]
        details = "自动化运维"
        [[params.skills.list.items]]
        details = "Redis/MySQL"
        [[params.skills.list.items]]
        details = "GitHub/Jenkins"
        [[params.skills.list.items]]
        details = "Prometheus/Grafana "
        [[params.skills.list.items]]
        details = "Kubenetes/Docker"

        [[params.skills.list]]
        title = "个人标签"
        [[params.skills.list.items]]
        details = "运动"
        [[params.skills.list.items]]
        details = "学习"
        [[params.skills.list.items]]
        details = "自律"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "计算机科学与技术"
        university = "南京工程学院"
        dates = "2021 - 2023"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true
        [[params.languages.list]]
        name = "英语"
        level = "学习中..."








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "长跑"
        [[params.interests.list]]
        name = "阅读"
        [[params.interests.list]]
        name = "滑板"
        [[params.interests.list]]
        name = "哲学"








    [params.summary]
        enable = true   
        text = "作为 90 后互联网从业者，我被人戏称为“陈老怪”。18 岁那年因在学校打架被通知家长，父亲要求我辍学后进入部队。之后我从事过多种职业，如房产中介、工人和开店。后来，我回想起小时候对计算机的兴趣，决定参加一个培训班学习服务器运维技术。尽管我更喜欢编程，但培训的老师建议我学习云计算相关技术，因为它有更好的就业前景。我完成了半年的学习，并获得了红帽认证工程师（RHCE）资格证书，从而进入了互联网行业。之后，我换了三份工作，因为没有统招学历（尽管后来通过函授的方式取得本科学历）只能找一些小的初创公司，结果要么是公司倒闭，要么是面临裁员。最近一份工作，我在签合同后才发现是一家外包公司，在运维岗位工作了一年后决定辞职，因为我想通过考研获得一个统招学历。虽然我初试没有达到国家线，但我在这几个月的学习中学到了很多知识，也对哲学和英语产生了兴趣。因此，即使我现在没有再次就业的打算，但我依然坚持学习哲学和英语，利用空闲时间阅读康德和学习语法。"







    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "中级运维工程师"
        dates = "2022-02 - 2023-04"
        company = "南京XX软件"
        details = "参与中国移动 Cloud 的基础建设工作，负责高可用 Kubernets 环境的部署，底层基础服务的部署，如部署 MySQL 高可用服务，Redis 集群部署，基于 K8S 环境的业务部署，以及一系列涉及到的中间件，tomcat、nginx、rabbitmq 等。"
        [[params.experience.list.items]]
        details = "中国移动项目"
        [[params.experience.list.items]]
        details = "苹果 iCloud 项目"
        [[params.experience.list]]
        title = "中级运维工程师"
        dates = "2020.10 - 2022.02"
        company = "南京XX网络科技有限公司"
        details = "负责阿里云服务器的维护，涉及 RDS、CND、域名服务等一系列运维。接管过公司 CI/CD 环境的搭建和完善，主要对自动构建出错时的通知功能。生成环境和测试环境 K8S 的日常维护。"
        [[params.experience.list.items]]
        details = "数据库/K8S"
        [[params.experience.list.items]]
        details = "网站维护."

        [[params.experience.list]]
        title = "初级运维工程师"
        dates = "2019-02 - 2020-10"
        company = "南京XX网络科技有限公司"
        details = "负责公司服务的日常运维，参与区块链技术的开发。对区块链服务器的日常更新维护。"
        [[params.experience.list.items]]
        details = "linux 环境配置"
        [[params.experience.list.items]]
        details = "监控脚本"











    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "爱好"
        details = "长跑, 滑板, 哲学"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/ohmykevin"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/941104c"
        title = "@941104c"